final Map<String, dynamic> gradesData = {
  "grades": {
    "เทอม 1 ปี 1": [
      {
        "code": "GEBLC101",
        "name": "ภาษาอังกฤษเพื่อการสื่อสารในชีวิตประจำวัน",
        "credits": 3,
        "grade": "B",
        "points": 9,
      },
      {
        "code": "GEBLC201",
        "name": "ศิลปะการใช้ภาษาไทย",
        "credits": 3,
        "grade": "C+",
        "points": 7.5,
      },
      {
        "code": "GEBIN705",
        "name": "แก่นวิศวกรรมซอฟต์แวร์",
        "credits": 3,
        "grade": "A",
        "points": 12,
      },
      {
        "code": "ENGSE200",
        "name": "วิศวกรรมซอฟต์แวร์เบื้องต้น",
        "credits": 3,
        "grade": "B",
        "points": 9,
      },
      {
        "code": "ENGSE201",
        "name": "กฎหมายและจริยธรรมด้านเทคโนโลยีสารสนเทศ",
        "credits": 1,
        "grade": "A",
        "points": 4,
      },
      {
        "code": "ENGSE217",
        "name": "การสื่อสารข้อมูลและเครือข่าย",
        "credits": 3,
        "grade": "C",
        "points": 6,
      },
      {
        "code": "ENGCC304",
        "name": "การเขียนโปรแกรมคอมพิวเตอร์",
        "credits": 3,
        "grade": "C",
        "points": 6,
      },
    ],
    "เทอม 2 ปี 1": [
      {
        "code": "GEBIN702",
        "name": "นวัตกรรมและเทคโนโลยี",
        "credits": 3,
        "grade": "A",
        "points": 12,
      },
      {
        "code": "ENGSE202",
        "name": "ระบบปฏิบัติการและการจัดโครงแบบเครื่องแม่ข่าย",
        "credits": 3,
        "grade": "C+",
        "points": 7.5,
      },
      {
        "code": "GEBLC103",
        "name": "ภาษาอังกฤษเชิงวิชาการ",
        "credits": 3,
        "grade": "B",
        "points": 10.5,
      },
      {
        "code": "ENGSE203",
        "name": "การเขียนโปรแกรมสำหรับวิศวกรซอฟต์แวร์",
        "credits": 3,
        "grade": "C+",
        "points": 7.5,
      },
      {
        "code": "ENGSE218",
        "name": "โครงสร้างและสถาปัตยกรรมคอมพิวเตอร์",
        "credits": 3,
        "grade": "B+",
        "points": 10.5,
      },
      {
        "code": "ENGSE216",
        "name": "โครงสร้างข้อมูลและขั้นตอนวิธี",
        "credits": 3,
        "grade": "D+",
        "points": 4.5,
      },
      {
        "code": "ENGSE206",
        "name": "การกำหนดความต้องการและการออกแบบทางซอฟต์แวร์",
        "credits": 3,
        "grade": "C+",
        "points": 7.5,
      },
    ],
    "เทอม 1 ปี 2": [
      {
        "code": "ENGSE101",
        "name": "คณิตศาสตร์ดิสครีต",
        "credits": 3,
        "grade": "D",
        "points": 3,
      },
      {
        "code": "ENGSE100",
        "name": "ความน่าจะเป็นและสถิติในงานวิศวกรรม",
        "credits": 3,
        "grade": "A",
        "points": 12,
      },
      {
        "code": "ENGSE204",
        "name": "การเขียนโปรแกรมเชิงวัตถุ",
        "credits": 3,
        "grade": "C",
        "points": 6,
      },
      {
        "code": "ENGSE205",
        "name": "กระบวนการซอฟต์แวร์และการประกันคุณภาพ",
        "credits": 3,
        "grade": "B",
        "points": 9,
      },
      {
        "code": "ENGSE219",
        "name": "ระบบฐานข้อมูล",
        "credits": 3,
        "grade": "C+",
        "points": 7.5,
      },
      {
        "code": "ENGSE503",
        "name": "การประมวลผลภาพดิจิทัล และการมองเห็นโดยคอมพิวเตอร์",
        "credits": 3,
        "grade": "B",
        "points": 9,
      },
      {
        "code": "GEBHT601",
        "name": "กิจกรรมเพื่อสุขภาพ",
        "credits": 3,
        "grade": "A",
        "points": 12,
      },
    ],
    "เทอม 2 ปี 2": [
      {
        "code": "GEBSO503",
        "name": "มนุษยสัมพันธ์",
        "credits": 3,
        "grade": "C",
        "points": 6,
      },
      {
        "code": "GEBSC301",
        "name": "เทคโนโลยีสารสนเทศที่จำเป็นในชีวิตประจำวัน",
        "credits": 3,
        "grade": "C+",
        "points": 7.5,
      },
      {
        "code": "ENGSE102",
        "name": "พีชคณิตเชิงเส้นสำหรับวิศวกรรม",
        "credits": 3,
        "grade": "C+",
        "points": 7.5,
      },
      {
        "code": "ENGSE207",
        "name": "สถาปัตยกรรมซอฟต์แวร์",
        "credits": 3,
        "grade": "B+",
        "points": 10.5,
      },
      {
        "code": "ENGRA017",
        "name": "ระบบอัตโนมัติในโรงงาน",
        "credits": 3,
        "grade": "B+",
        "points": 10.5,
      },
      {
        "code": "ENGSE502",
        "name": "ระบบฝังตัวและระบบอินเทอร์เน็ตในทุกสิ่ง",
        "credits": 3,
        "grade": "B",
        "points": 10.5,
      },
      {
        "code": "BBAIS823",
        "name": "การใช้โปรแกรมสำนักงานสมัยใหม่",
        "credits": 3,
        "grade": "B",
        "points": 9,
      },
    ],
    "เทอม 1 ปี 3": [
      {
        "code": "ENGSE301",
        "name": "Software Testing",
        "credits": 3,
        "grade": "A",
        "points": 12,
      },
      {
        "code": "ENGSE302",
        "name": "Web Development",
        "credits": 3,
        "grade": "A",
        "points": 12,
      },
      {
        "code": "ENGSE303",
        "name": "Project Management",
        "credits": 3,
        "grade": "A",
        "points": 12,
      },
      {
        "code": "ENGSE304",
        "name": "AI Fundamentals",
        "credits": 3,
        "grade": "A",
        "points": 12,
      },
      {
        "code": "ENGSE305",
        "name": "Network Security",
        "credits": 3,
        "grade": "A",
        "points": 12,
      },
      {
        "code": "GEBSC401",
        "name": "Ethics in IT",
        "credits": 3,
        "grade": "A",
        "points": 12,
      },
      {
        "code": "ENGSE306",
        "name": "Final Project",
        "credits": 3,
        "grade": "A",
        "points": 12,
      },
    ],
  },
};
